# Generated by Django 3.1.4 on 2021-03-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_auto_20210327_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='mascot_profile'),
        ),
    ]
