# Generated by Django 3.1.4 on 2021-03-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_auto_20210327_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
