# Generated by Django 3.1.4 on 2021-04-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0004_auto_20210329_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='clinica_profile'),
        ),
    ]
