# Generated by Django 3.1.4 on 2021-04-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0005_auto_20210405_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabaja',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
