# Generated by Django 3.1.7 on 2021-04-17 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0006_auto_20210413_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='trabajores',
            field=models.ManyToManyField(related_name='clininas', to=settings.AUTH_USER_MODEL),
        ),
    ]
